name: gest_hab
description: "A new Flutter project."

# This line prevents accidental publication to pub.dev
publish_to: 'none'

# Versioning for the application
version: 1.0.0+1

# Minimum environment requirement for Dart
environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Firebase dependencies
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.0
  cloud_firestore: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  # Enables the use of Material Design icons
  uses-material-design: true
  assets:
    - lib/assets/facebook.png
    - lib/assets/google.png

  # Uncomment this section to add assets to your app
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # Uncomment this section to add custom fonts
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
